config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#delete'
  resources :posts, only: [:new, :create, :index]

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_secure_password
  before_create :remember

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    Digest::SHA1.hexdigest(string)
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token.to_s))
  end

  def authenticated?(remember_token)
    if remember_digest && remember_token
      remember_digest == User.digest(remember_token)
    else
      false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

  def log_in(user)
    # Do the cookies stuff here and the user's attributes in the User model
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def sign_out
    current_user = nil
    cookies.permanent[:remember_token] = nil
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    if @post.save
      flash[:success] = "New post created!"
      redirect_to '/posts'
    else
      flash[:danger].now = "Couldn't create the post"
      render '/new'
    end
  end

  def index
    @posts = Post.all
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in"
        redirect_to '/posts'
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      flash.now[:success] = "Logged in"
      log_in @user
      redirect_to posts_url
    else
      flash.now[:danger] = "Credentials not recognised, please try again"
      render 'new'
    end
  end

  def delete
    sign_out
    flash[:success] = "Logged out"
    redirect_to posts_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= lookup_current_user
  end

  def lookup_current_user
    if (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user.authenticated?(cookies[:remember_token])
        user
      else
        nil
      end
    else
      nil
    end
  end

  def current_user=(user)
    log_in user
    @current_user = user
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def find_username(user_id)
    User.find_by(id: user_id).username
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <ul class="menu">
      <% if logged_in? %><li class="menu-item"><%= link_to "Sign out", logout_path, class: "menu-item", method: :delete %></li><% end %>
      <% if !logged_in? %><li class="menu-item"><%= link_to "Sign in", login_path, class: "menu-item" %></li><% end %>
    </ul>
  </div>
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>All posts</h1>

<%= link_to "Create a new post", new_post_url %>

<% @posts.each do |p| %>
  <p class="post-title">
    <%= p.title %>
    <% if logged_in? %>
      <span class="post-author"> posted by <%= find_username(p.user_id) %></span>
    <% end %>
  </p>
  <div class="post">
    <%= p.body %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Write a new post</h1>

<%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body, "Post" %>
  <%= f.text_area :body, size: "60x12" %>

  <%= f.submit "Post" %>

<% end %>